//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpHomeSecurity.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tImage
    {
        public System.Guid ImageId { get; set; }
        public Nullable<System.Guid> AlbumId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
    
        public virtual tAlbum tAlbum { get; set; }
    }
}
