//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpHomeSecurity.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTestimonial
    {
        public System.Guid TestimonialId { get; set; }
        public string Testimonial { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ByName { get; set; }
        public string Location { get; set; }
    }
}
